import { StyleSheet } from 'react-native';
import type { AppThemeColors } from '../../theme/themes';
import { createCommonStyles } from '../../theme/commonStyles';

export function createStyles(colors: AppThemeColors) {
  const common = createCommonStyles(colors);

  return StyleSheet.create({
    safeArea: common.safeArea,
    emptyCard: common.emptyCard,
    emptyTitle: common.emptyTitle,
    emptySubtitle: common.emptySubtitle,
    modalOverlay: common.modalOverlay,

    content: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 32,
      gap: 14,
    },
    apiaryHeaderTag: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.accentSoft,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
      alignSelf: 'flex-start',
    },
    apiaryTagText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.headerBackground,
    },
    searchInput: {
      height: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      fontSize: 14,
      color: colors.textPrimary,
    },
    boxCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 6,
      elevation: 1,
      gap: 14,
    },
    boxCardHandled: {
      borderColor: '#059669',
      borderWidth: 1.8,
      backgroundColor: colors.surface,
    },
    handledBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: '#ECFDF5',
      borderWidth: 1,
      borderColor: '#A7F3D0',
      paddingHorizontal: 8,
      paddingVertical: 2.5,
      borderRadius: 8,
    },
    handledBadgeText: {
      fontSize: 11,
      fontWeight: '800',
      color: '#059669',
    },
    boxCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    boxTitleArea: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    boxIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: colors.accentSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    boxIconWrapHandled: {
      backgroundColor: '#ECFDF5',
    },
    boxName: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    boxApiaryName: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
    },
    headerButtons: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    iconBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardBottomActions: {
      flexDirection: 'row',
      gap: 10,
    },
    mainActionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 10,
      borderRadius: 10,
    },
    mainActionBtnText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '700',
    },
    modalContent: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      width: '88%',
      borderWidth: 1,
      borderColor: colors.cardBorder,
    },
    modalHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.textPrimary,
      marginBottom: 14,
    },
    modalInput: {
      height: 48,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      paddingHorizontal: 14,
      fontSize: 15,
      color: colors.textPrimary,
      marginBottom: 18,
    },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 10,
    },
    modalBtn: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
    },
    cancelBtn: {
      backgroundColor: colors.background,
    },
    cancelBtnText: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '600',
    },
    saveBtn: {
      backgroundColor: colors.headerBackground,
    },
    saveBtnText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '700',
    },
    historyItem: {
      padding: 12,
      backgroundColor: colors.background,
      borderRadius: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.cardBorder,
    },
    historyHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
    },
    historyTag: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.headerBackground,
      backgroundColor: '#E0F2F1',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 4,
    },
    historyDate: {
      fontSize: 11,
      color: colors.textMuted,
    },
    historyText: {
      fontSize: 13,
      color: colors.textPrimary,
      marginTop: 4,
      lineHeight: 18,
    },
  });
}
