import { StyleSheet } from 'react-native';
import type { AppThemeColors } from '../../theme/themes';
import { createCommonStyles } from '../../theme/commonStyles';

export function createStyles(colors: AppThemeColors) {
  const common = createCommonStyles(colors);

  return StyleSheet.create({
    safeArea: common.safeArea,
    loader: common.loader,

    floatingTranscript: {
      position: 'absolute',
      top: 100,
      left: 18,
      right: 18,
      backgroundColor: colors.accent,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 14,
      zIndex: 1000,
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
    },
    floatingTranscriptText: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '600',
      fontStyle: 'italic',
      textAlign: 'center',
    },
    content: {
      paddingHorizontal: 18,
      paddingTop: 14,
      paddingBottom: 130,
      gap: 16,
    },
    heroCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 16,
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 6,
      elevation: 1,
    },
    heroIconBadge: {
      width: 46,
      height: 46,
      borderRadius: 14,
      backgroundColor: '#FEF3C7',
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroBoxTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    heroApiaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    heroApiaryText: {
      fontSize: 13,
      color: colors.textMuted,
      fontWeight: '500',
    },
    activeManejoBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: '#FEF3C7',
      borderWidth: 1,
      borderColor: '#FCD34D',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 10,
    },
    pulsingDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#D97706',
    },
    activeManejoBadgeText: {
      fontSize: 11.5,
      fontWeight: '700',
      color: '#D97706',
    },
    voiceCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      backgroundColor: colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.03,
      shadowRadius: 5,
      elevation: 1,
    },
    voiceCardActive: {
      backgroundColor: '#FEF3C7',
      borderColor: '#D97706',
    },
    voiceIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: '#FEF3C7',
      alignItems: 'center',
      justifyContent: 'center',
    },
    voiceIconWrapActive: {
      backgroundColor: '#D97706',
    },
    voiceTextWrap: {
      flex: 1,
      gap: 2,
    },
    voiceTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    voiceSubtitle: {
      fontSize: 12,
      color: colors.textMuted,
    },
    recordingPill: {
      backgroundColor: '#D97706',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
    },
    recordingPillText: {
      fontSize: 10,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    sectionBlock: {
      gap: 10,
    },
    sectionHeader: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.textMuted,
      letterSpacing: 0.8,
      marginLeft: 4,
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      paddingBottom: 4,
    },
    taskContainer: {
      width: '48.3%',
    },
    activeTaskContainer: {
      width: '100%',
      gap: 10,
      marginBottom: 6,
    },
    optionCard: {
      width: '100%',
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 18,
      paddingHorizontal: 12,
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 2,
      borderColor: colors.cardBorder,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      elevation: 2,
    },
    optionCardActive: {
      backgroundColor: '#D97706',
      borderColor: '#B45309',
    },
    optionText: {
      fontSize: 17,
      fontWeight: '700',
      textAlign: 'center',
      color: colors.textPrimary,
    },
    optionTextActive: {
      color: '#FFFFFF',
      fontWeight: '900',
    },
    taskNotes: {
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1.5,
      borderColor: colors.cardBorder,
      padding: 16,
      gap: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.03,
      shadowRadius: 4,
      elevation: 1,
    },
    taskInput: {
      minHeight: 95,
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: colors.cardBorder,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 17,
      fontWeight: '600',
      lineHeight: 24,
      color: colors.textPrimary,
      textAlignVertical: 'top',
    },
    fieldHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    fieldLabel: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    voiceFieldBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: '#FEF3C7',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
    },
    voiceFieldBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#D97706',
    },
    voicePreview: {
      fontSize: 15,
      fontWeight: '600',
      color: '#D97706',
      fontStyle: 'italic',
      paddingHorizontal: 2,
    },
    concluirTaskBtn: {
      marginTop: 6,
      minHeight: 48,
      backgroundColor: '#FEF3C7',
      borderWidth: 1.5,
      borderColor: '#FCD34D',
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    concluirTaskBtnText: {
      color: '#92400E',
      fontWeight: '800',
      fontSize: 16,
    },
    photoSection: {
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1.5,
      borderColor: colors.cardBorder,
      padding: 16,
      gap: 12,
    },
    photoButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.cardBorder,
      backgroundColor: colors.surface,
      paddingVertical: 16,
      paddingHorizontal: 14,
    },
    photoButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    photoPreviewContainer: {
      position: 'relative',
      borderRadius: 14,
      overflow: 'hidden',
    },
    photoPreview: {
      width: '100%',
      height: 220,
      borderRadius: 14,
    },
    removePhotoBtn: {
      position: 'absolute',
      top: 10,
      right: 10,
      backgroundColor: 'rgba(255,255,255,0.92)',
      borderRadius: 14,
      padding: 4,
    },
    actionsArea: {
      marginTop: 8,
      paddingBottom: 10,
    },
    primaryAction: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      paddingVertical: 16,
      borderRadius: 16,
      backgroundColor: '#D97706',
      shadowColor: '#D97706',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    primaryActionText: {
      fontSize: 18,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
  });
}
