import { StyleSheet } from 'react-native';
import type { AppThemeColors } from './themes';

export function createCommonStyles(colors: AppThemeColors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    listContent: {
      paddingTop: 18,
      paddingHorizontal: 18,
      paddingBottom: 24,
      gap: 12,
      overflow: 'hidden',
    },
    glowOne: {
      position: 'absolute',
      top: 36,
      right: -34,
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: colors.glowA,
      opacity: 0.2,
    },
    glowTwo: {
      position: 'absolute',
      bottom: 120,
      left: -38,
      width: 140,
      height: 140,
      borderRadius: 70,
      backgroundColor: colors.glowB,
      opacity: 0.16,
    },
    loader: {
      marginVertical: 24,
    },
    card: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      backgroundColor: colors.card,
      paddingHorizontal: 16,
      paddingVertical: 14,
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    emptyCard: {
      minHeight: 120,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      backgroundColor: colors.card,
      paddingHorizontal: 16,
      paddingVertical: 20,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    emptyIcon: {
      marginBottom: 8,
    },
    emptyTitle: {
      fontSize: 18,
      lineHeight: 24,
      color: colors.textPrimary,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    emptySubtitle: {
      marginTop: 4,
      fontSize: 15,
      lineHeight: 20,
      color: colors.textMuted,
      textAlign: 'center',
    },
    inputLabel: {
      fontSize: 16,
      color: colors.textPrimary,
      fontWeight: '600',
      marginBottom: 6,
    },
    inputContainer: {
      marginBottom: 16,
    },
    input: {
      minHeight: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      color: colors.textPrimary,
      paddingHorizontal: 16,
      fontSize: 16,
    },
    button: {
      minHeight: 52,
      borderRadius: 12,
      backgroundColor: colors.buttonBackground,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    buttonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.buttonText,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      padding: 20,
    },
    modalContent: {
      maxHeight: '80%',
      backgroundColor: colors.background,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.cardBorder,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 5,
    },
  });
}
